version: '2.0'
services:
  timely:
    image: timely
    build: .
    ports:
     - "9804:9804" # standalone zookeeper
     - "54321:54321" # timely put
     - "54322:54322" # timely query
    volumes:
     - ${PWD}/:/timely-server-src
    command: /timely-server-src/bin/docker/deploy-startup-standalone.sh
    environment:
     - LD_LIBRARY_PATH=/timely/bin/META-INF/native
     - TIMELY_VERSION=0.0.2-SNAPSHOT
  ingest:
    image: timely
    entrypoint: /timely-server-src/bin/docker/deploy-wait-and-insert.sh
    volumes:
     - ${PWD}/:/timely-server-src
    depends_on:
     - timely
    environment:
     - TIMELY_HOST=timely
     - TIMELY_PORT=54321
  grafana:
    image: grafana/grafana
    ports:
     - "3000:3000"
    volumes:
     - ${PWD}/../grafana/timely-app:/var/lib/grafana/plugins/timely-app
    depends_on:
     - timely