services:
  grafana:
    user: root
    container_name: 'grafana-timely-datasource'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-oss}
        grafana_version: ${GRAFANA_VERSION:-11.5.2}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./dist:/var/lib/grafana/plugins/timely-datasource
      - ./data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/timely-datasource
      - ./pki:/etc/pki

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.timely-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_SECURITY_COOKIE_SECURE: true
      GF_USERS_AUTO_ASSIGN_ORG_ROLE: Editor
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: timely-datasource
      GF_SERVER_ENFORCE_DOMAIN: true
      GF_SERVER_CERT_FILE: /etc/pki/testServer.cert
      GF_SERVER_CERT_KEY: /etc/pki/testServer.key
      GF_SERVER_PROTOCOL: https
      # set hostname or ip that is used in the browser
      GF_SERVER_DOMAIN: localhost
